# Generated by Django 5.1.6 on 2025-03-05 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_product_product_type_size_size_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='subtype',
            field=models.CharField(default='top', max_length=20),
            preserve_default=False,
        ),
    ]
